in_amount = "0x29a2241af62c0000"
in_asset_id = "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
in_blinding = "0x4f349c6eff27c6808a39a7cc44740325e526a2557085c785cea9f41815b3c4"
in_priv_key = "0x92b6d245df0d5631e3043c4c433cba7aafbd40421924492cde650c13167337"
in_path = ["0x0", "0x0"]
in_siblings = ["0x0", "0x98f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864"]
change_amount = "0x0"
change_blinding = "0x8547f6612d2b020c4b62bc801fc6f5c53a341799d7b66637eebe6f3b1c0654"
change_pub_key = "0x4ef83092a9e40fbd8348576811fc28fde2d39798077405490e9a7069c53682a"
merkle_root = "0x47ca23ec96060069941e2944476c556806aa484efcb36de22f33e5843dee619"
nullifier = "0xc6c5aae8894c9de496148fb18148884ad4ae5caa2e66cc1e7a01475ad49f4d"
change_commitment = "0x7b431237d413d076647633e52f7ae2e2f0af4358785d8f3661aea33b446c66b"
recipient = "0x2c402cda5fa6c196c87b2282f92cacf1194e353a279ed9a82141ab2f6262f7a"
withdraw_amount = "0x29a2241af62c0000"
