commitment_1 = ""
commitment_2 = ""
in1_amount = ""
in1_asset_id = ""
in1_blinding = ""
in1_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in1_priv_key = ""
in1_siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in2_amount = ""
in2_asset_id = ""
in2_blinding = ""
in2_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in2_priv_key = ""
in2_siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkle_root = ""
nullifier_1 = ""
nullifier_2 = ""
out1_amount = ""
out1_blinding = ""
out1_pub_key = ""
out2_amount = ""
out2_blinding = ""
out2_pub_key = ""
relayer_fee = ""
